[2024-08-21T09:48:10.822+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T09:48:10.831+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.sleep scheduled__2024-08-21T00:44:00+00:00 [queued]>
[2024-08-21T09:48:10.837+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.sleep scheduled__2024-08-21T00:44:00+00:00 [queued]>
[2024-08-21T09:48:10.837+0700] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-21T09:48:10.854+0700] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): sleep> on 2024-08-21 00:44:00+00:00
[2024-08-21T09:48:10.858+0700] {standard_task_runner.py:72} INFO - Started process 57204 to run task
[2024-08-21T09:48:10.861+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'sleep', 'scheduled__2024-08-21T00:44:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/daily_report.py', '--cfg-path', '/tmp/tmpf6k3milt']
[2024-08-21T09:48:10.862+0700] {standard_task_runner.py:105} INFO - Job 79: Subtask sleep
[2024-08-21T09:48:10.894+0700] {task_command.py:467} INFO - Running <TaskInstance: simple_dag.sleep scheduled__2024-08-21T00:44:00+00:00 [running]> on host LAPTOP-G8FSBU09.
[2024-08-21T09:48:10.949+0700] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='sleep' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:44:00+00:00'
[2024-08-21T09:48:10.950+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-21T09:48:10.950+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-21T09:48:10.950+0700] {logging_mixin.py:190} INFO - Current task name:sleep state:running start_date:2024-08-21 02:48:10.832016+00:00
[2024-08-21T09:48:10.950+0700] {logging_mixin.py:190} INFO - Dag name:simple_dag and current dag run status:running
[2024-08-21T09:48:10.950+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T09:48:10.952+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T09:48:10.953+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2024-08-21T09:48:10.960+0700] {subprocess.py:86} INFO - Output:
[2024-08-21T09:48:13.629+0700] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-21T09:48:13.633+0700] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 57204. PIDs of all processes in the group: [57206, 57204]
[2024-08-21T09:48:13.633+0700] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 57204
[2024-08-21T09:48:13.634+0700] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-21T09:48:13.634+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-08-21T09:48:13.642+0700] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/user/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3085, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-21T09:48:13.651+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-21T09:48:13.651+0700] {logging_mixin.py:190} INFO - Task start:2024-08-21 02:48:10.832016+00:00 end:2024-08-21 02:48:13.650640+00:00 duration:2.818624
[2024-08-21T09:48:13.651+0700] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): sleep> dag:<DAG: simple_dag> dagrun:<DagRun simple_dag @ 2024-08-21 00:44:00+00:00: scheduled__2024-08-21T00:44:00+00:00, state:running, queued_at: 2024-08-21 02:47:55.080597+00:00. externally triggered: False>
[2024-08-21T09:48:13.651+0700] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-08-21T09:48:13.651+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=sleep, run_id=scheduled__2024-08-21T00:44:00+00:00, execution_date=20240821T004400, start_date=20240821T024810, end_date=20240821T024813
[2024-08-21T09:48:13.667+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T09:48:13.686+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=57206, status='terminated', started='09:48:10') (57206) terminated with exit code None
[2024-08-21T09:48:13.686+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=57204, status='terminated', exitcode=2, started='09:48:10') (57204) terminated with exit code 2
[2024-08-21T09:48:18.754+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T09:48:18.759+0700] {taskinstance.py:2593} INFO - Dependencies not met for <TaskInstance: simple_dag.sleep scheduled__2024-08-21T00:44:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-08-21T02:48:18.759186+00:00 and task will be retried at 2024-08-21T02:50:13.650640+00:00.
[2024-08-21T09:48:18.763+0700] {local_task_job_runner.py:166} INFO - Task is not able to be run
