[2024-08-22T11:26:17.950+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-22T11:26:17.959+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqlite_query_dag.query_sqlite_users scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2024-08-22T11:26:17.962+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqlite_query_dag.query_sqlite_users scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2024-08-22T11:26:17.963+0700] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-22T11:26:17.974+0700] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): query_sqlite_users> on 2023-01-08 00:00:00+00:00
[2024-08-22T11:26:17.977+0700] {standard_task_runner.py:72} INFO - Started process 36790 to run task
[2024-08-22T11:26:17.979+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sqlite_query_dag', 'query_sqlite_users', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/test_slqite.py', '--cfg-path', '/tmp/tmpsstlc_tb']
[2024-08-22T11:26:17.980+0700] {standard_task_runner.py:105} INFO - Job 15: Subtask query_sqlite_users
[2024-08-22T11:26:18.010+0700] {task_command.py:467} INFO - Running <TaskInstance: sqlite_query_dag.query_sqlite_users scheduled__2023-01-08T00:00:00+00:00 [running]> on host LAPTOP-G8FSBU09.
[2024-08-22T11:26:18.057+0700] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sqlite_query_dag' AIRFLOW_CTX_TASK_ID='query_sqlite_users' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2024-08-22T11:26:18.058+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-22T11:26:18.059+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-22T11:26:18.059+0700] {logging_mixin.py:190} INFO - Current task name:query_sqlite_users state:running start_date:2024-08-22 04:26:17.959679+00:00
[2024-08-22T11:26:18.059+0700] {logging_mixin.py:190} INFO - Dag name:sqlite_query_dag and current dag run status:running
[2024-08-22T11:26:18.059+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-22T11:26:18.059+0700] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/user/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/user/airflow/dags/test_slqite.py", line 31, in query_sqlite_users
    conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
[2024-08-22T11:26:18.065+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-22T11:26:18.065+0700] {logging_mixin.py:190} INFO - Task start:2024-08-22 04:26:17.959679+00:00 end:2024-08-22 04:26:18.065285+00:00 duration:0.105606
[2024-08-22T11:26:18.065+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): query_sqlite_users> dag:<DAG: sqlite_query_dag> dagrun:<DagRun sqlite_query_dag @ 2023-01-08 00:00:00+00:00: scheduled__2023-01-08T00:00:00+00:00, state:running, queued_at: 2024-08-22 04:26:16.176653+00:00. externally triggered: False>
[2024-08-22T11:26:18.066+0700] {logging_mixin.py:190} INFO - Failure caused by unable to open database file
[2024-08-22T11:26:18.066+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=sqlite_query_dag, task_id=query_sqlite_users, run_id=scheduled__2023-01-08T00:00:00+00:00, execution_date=20230108T000000, start_date=20240822T042617, end_date=20240822T042618
[2024-08-22T11:26:18.077+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-22T11:26:18.078+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task query_sqlite_users (unable to open database file; 36790)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/user/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/user/airflow/dags/test_slqite.py", line 31, in query_sqlite_users
    conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
[2024-08-22T11:26:18.112+0700] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-22T11:26:18.121+0700] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T11:26:18.121+0700] {local_task_job_runner.py:240} INFO - ::endgroup::
